In [2]:
import numpy as np

In [3]:
# creates an array with random content
np.empty(shape=(2,4))

array([[-1.28822975e-231, -2.32035276e+077,  2.47032823e-323,
         0.00000000e+000],
       [ 0.00000000e+000,  0.00000000e+000, -1.28822975e-231,
         2.00389576e+000]])

In [4]:
# creates an array with ones
np.ones(shape=(2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [5]:
# creates an array with zeros
np.zeros(shape=(2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [6]:
np.full(shape=(3,3), fill_value=5)


array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [7]:
# creates a n * n matrix with the diagonal 1s and the others 0.
np.eye(N=5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [8]:
# creates an array with values ranging from 0 to n.
np.arange(start=24)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [9]:
np.arange(start=0, stop=20, step=2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [10]:
# linspace returns evenly spaced numbers over a specified interval.
np.linspace(start=0,stop=20,num=2)

array([ 0., 20.])

In [11]:
# arange outputs a one-dimensional array. To make it a two-dimensional array, chain its output with the reshape function
np.arange(24).reshape(-1, 2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [12]:
a = np.arange(24).reshape(-1, 2)
np.transpose(a=a)

array([[ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22],
       [ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23]])

In [13]:
np.random.random(20).reshape(-1,2)

array([[0.0942624 , 0.75492981],
       [0.17966292, 0.34688791],
       [0.418862  , 0.48343978],
       [0.51042347, 0.92295391],
       [0.56610256, 0.17969855],
       [0.21124557, 0.52512157],
       [0.23445976, 0.93438263],
       [0.18080933, 0.62966067],
       [0.07879402, 0.76613151],
       [0.97551201, 0.09682526]])

In [14]:
a = np.arange(10)
for _ in range(9):
    a = np.vstack((a, np.arange(10)))
a, a.shape

(array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]]),
 (10, 10))

In [15]:
a = a.T
a

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [6, 6, 6, 6, 6, 6, 6, 6, 6, 6],
       [7, 7, 7, 7, 7, 7, 7, 7, 7, 7],
       [8, 8, 8, 8, 8, 8, 8, 8, 8, 8],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9]])

In [16]:
a[1:,:]

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [6, 6, 6, 6, 6, 6, 6, 6, 6, 6],
       [7, 7, 7, 7, 7, 7, 7, 7, 7, 7],
       [8, 8, 8, 8, 8, 8, 8, 8, 8, 8],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9]])

In [17]:
a[:,1], a[:,1].shape

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), (10,))

In [18]:
a[:,[5]], a[:,[5]].shape

(array([[0],
        [1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]]),
 (10, 1))

In [19]:
a[:,:3]

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2],
       [3, 3, 3],
       [4, 4, 4],
       [5, 5, 5],
       [6, 6, 6],
       [7, 7, 7],
       [8, 8, 8],
       [9, 9, 9]])

In [20]:
a[:,2:6]

array([[0, 0, 0, 0],
       [1, 1, 1, 1],
       [2, 2, 2, 2],
       [3, 3, 3, 3],
       [4, 4, 4, 4],
       [5, 5, 5, 5],
       [6, 6, 6, 6],
       [7, 7, 7, 7],
       [8, 8, 8, 8],
       [9, 9, 9, 9]])

In [21]:
a[:,5:-1]

array([[0, 0, 0, 0],
       [1, 1, 1, 1],
       [2, 2, 2, 2],
       [3, 3, 3, 3],
       [4, 4, 4, 4],
       [5, 5, 5, 5],
       [6, 6, 6, 6],
       [7, 7, 7, 7],
       [8, 8, 8, 8],
       [9, 9, 9, 9]])

In [22]:
a[2:-4,:]

array([[2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5]])

In [23]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
np.stack((arr1, arr2), axis=0)

array([[1, 2, 3],
       [4, 5, 6]])

In [24]:
np.stack((arr1, arr2), axis=1)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [25]:
np.vstack((arr1,arr2))

array([[1, 2, 3],
       [4, 5, 6]])

In [26]:
np.hstack((arr1,arr2))


array([1, 2, 3, 4, 5, 6])

Operations

In [27]:
arr_6x3_2 = np.full(shape=(6,3),fill_value=2)
arr_6x3_2

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2],
       [2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [28]:
arr_6x3_3 = np.full(shape=(6,3),fill_value=3)
arr_6x3_3

array([[3, 3, 3],
       [3, 3, 3],
       [3, 3, 3],
       [3, 3, 3],
       [3, 3, 3],
       [3, 3, 3]])

In [29]:
arr_6x3_4 = np.full(shape=(3,2),fill_value=4)
arr_6x3_4

array([[4, 4],
       [4, 4],
       [4, 4]])

In [30]:
# Elementwise sum, substraction, multiplication, division
arr_6x3_2 + arr_6x3_3, arr_6x3_2 - arr_6x3_3, arr_6x3_2 * arr_6x3_3, arr_6x3_2 / arr_6x3_3

(array([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5],
        [5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]]),
 array([[-1, -1, -1],
        [-1, -1, -1],
        [-1, -1, -1],
        [-1, -1, -1],
        [-1, -1, -1],
        [-1, -1, -1]]),
 array([[6, 6, 6],
        [6, 6, 6],
        [6, 6, 6],
        [6, 6, 6],
        [6, 6, 6],
        [6, 6, 6]]),
 array([[0.66666667, 0.66666667, 0.66666667],
        [0.66666667, 0.66666667, 0.66666667],
        [0.66666667, 0.66666667, 0.66666667],
        [0.66666667, 0.66666667, 0.66666667],
        [0.66666667, 0.66666667, 0.66666667],
        [0.66666667, 0.66666667, 0.66666667]]))

In [31]:
arr_6x3_2 + 5, arr_6x3_2 - 5, arr_6x3_2 * 5, arr_6x3_2 / 5

(array([[7, 7, 7],
        [7, 7, 7],
        [7, 7, 7],
        [7, 7, 7],
        [7, 7, 7],
        [7, 7, 7]]),
 array([[-3, -3, -3],
        [-3, -3, -3],
        [-3, -3, -3],
        [-3, -3, -3],
        [-3, -3, -3],
        [-3, -3, -3]]),
 array([[10, 10, 10],
        [10, 10, 10],
        [10, 10, 10],
        [10, 10, 10],
        [10, 10, 10],
        [10, 10, 10]]),
 array([[0.4, 0.4, 0.4],
        [0.4, 0.4, 0.4],
        [0.4, 0.4, 0.4],
        [0.4, 0.4, 0.4],
        [0.4, 0.4, 0.4],
        [0.4, 0.4, 0.4]]))

In [32]:
# Matrix multiplication
np.matmul(arr2, arr_6x3_4)
arr_6x3_2 @ arr_6x3_4


array([[24, 24],
       [24, 24],
       [24, 24],
       [24, 24],
       [24, 24],
       [24, 24]])

In [33]:
# sum all elements
np.sum(arr_6x3_2)

36

In [34]:
np.sum(arr_6x3_2, axis=0)

array([12, 12, 12])

In [35]:
sum(arr_6x3_2)

array([12, 12, 12])

In [36]:
np.sum(arr_6x3_2, axis=1)

array([6, 6, 6, 6, 6, 6])

In [37]:
arr_6x3_2**3

array([[8, 8, 8],
       [8, 8, 8],
       [8, 8, 8],
       [8, 8, 8],
       [8, 8, 8],
       [8, 8, 8]])

Search

In [38]:
y = np.arange(start=24, step=2)
y

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22])

In [39]:
np.where(y % 4 == 0)

(array([ 0,  2,  4,  6,  8, 10]),)

In [67]:
a[...,:-5]


array([[ 0,  0,  0,  0,  0],
       [11, 11, 11, 11, 11],
       [22, 22, 22, 22, 22],
       [33, 33, 33, 33, 33],
       [44, 44, 44, 44, 44],
       [55, 55, 55, 55, 55],
       [66, 66, 66, 66, 66],
       [77, 77, 77, 77, 77],
       [88, 88, 88, 88, 88],
       [99, 99, 99, 99, 99]])